Add SVG tutorial
codebar/tutorials pull request #327
Opened 2016-12-03 16:20 UTC by daniellevass

Hi All,

@mercebc and I have been working on an initial draft for an SVG tutorial. What do you think? 

Unsure about whether we should add a section for how to make path objects, or whether that might be too much for one tutorial?

The intention is to also have a part 2 to animate the emoji made using JavaScript.

Thank you 😄

2016-12-03 16:23 UTC, KimberleyCook commented on js/lesson6-1/tutorial.md
> +Speak to your coach if your unsure about the z index, or how the points property works. For more information you could look at [http://www.w3schools.com/graphics/svg_polygon.asp](http://www.w3schools
you're not your

2016-12-03 16:26 UTC, KimberleyCook commented on js/lesson6-1/tutorial.md
> +There are also some other svg shapes that might be useful, such as lines, ellipses, and text. Work with your coach, and look at W3 Schools for more ideas: [http://www.w3schools.com/graphics/svg_intro
After this sentence could we add: 

"This ends our firts of 2 lessons on SVG, we hope you enjoyed it and learnt something. If you have some spare time how about going back through this tutorial and, by yourself, make some amendments. If there is something you did not understand or want to give us some feedback, please send us an email"

2016-12-03 16:27 UTC, KimberleyCook requested changes
Hey, added one lil comment. 

The final sentence comment is what is just at the end of all tutorials so needs to be there for consistency.

Thank you very much, this is really really great :D :D

2017-01-04 15:41 UTC, KimberleyCook commented
@daniellevass @mercebc Just reminding you both of these little amends as I'd love to merge this in as it's great :)

2017-02-02 10:38 UTC, matyikriszta commented
@mercebc @daniellevass what is the status of this issue? We would love to merge it in and add it to the tutorials 😄

2018-12-01 13:38 UTC, brunogirin commented
This issue doesn't seem to have moved much for a year and I'd be interested in picking this up. However, I had in mind a more complex tutorial that covers multiple lessons, as I explained in [the SVG and canvas issue](https://github.com/codebar/tutorials/issues/100#issuecomment-443415227). Would that work?

2019-03-12 03:56 UTC, closed without merging